### ISSUE TITLE
Small review issues

### ISSUE THREAD

**Issue by ctb** [jdidion/xphyle#11]
This is a running issue for items associated with [my review for JOSS](https://github.com/openjournals/joss-reviews/issues/255).

- [x] a pointer to the github issue tracker should probably be added in the README, as obvious as it is...
- [x] an explicit pointer to the stable docs on readthedocs could be added (https://xphyle.readthedocs.io/en/stable/) - the little 'docs' button is not always so clear and in any case points to latest/ which might not be a release.
- [x] maybe spellcheck the docs? I found 'miscelanenous' while reading.
- [x] maybe have 'make test' run 'python -m pytest' for those of us using too many virtualenvs and with lazy install habits. (Not a big deal, obviously.)

**Comment by jdidion** [comment]
Hmm..mock is part of the unittest package starting in python 3.3. I am testing against all versions of python 3.3-3.7 with travis and it works fine without including mock as a dependency.

**Comment by ctb** [comment]
yep, that was a holdover from a silly problem I had w/versions. I already updated the issue but you must have been working off the e-mail :)

**Comment by jdidion** [comment]
Fixed in 06e53d2
