### ISSUE TITLE
`FileTests.test_system_lzma` fails on my laptop

### ISSUE THREAD

**Issue by ctb** [jdidion/xphyle#12]
```FileTests.test_system_lzma ``` fails on my computer -- I get

E               PermissionError: [Errno 13] Permission denied

```
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:1544: PermissionError
=============== 1 failed, 129 passed, 3 skipped in 19.27 seconds ===============
```

any ideas how to diagnose?

thx!

**Comment by jdidion** [comment]
It would be helpful to have the full stack trace. In the most recent commit, I added to the makefile the ability to specify additional pytest options. Try running:

make test "pytestopts=--full-trace"

**Comment by ctb** [comment]
> make test "pytestopts=--full-trace"


% python -m pytest -m "not perf" --cov --cov-report term-missing --full-trace tests
============================= test session starts ==============================
platform darwin -- Python 3.5.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/t/dev/xphyle, inifile:
plugins: cov-2.5.1
collected 135 items

tests/test_formats.py .s.......ss.........F.....
tests/test_paths.py ...................................
tests/test_progress.py ...
tests/test_types.py .....
tests/test_urls.py ....
tests/test_utils.py .....................................
tests/test_xphyle.py .......................

---------- coverage: platform darwin, python 3.5.1-final-0 -----------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
xphyle/__init__.py     491     14    97%   285, 291, 391, 395-405, 612, 684, 826
xphyle/formats.py      523     23    96%   191, 292, 298, 508, 540-541, 640-641, 773, 790, 832-842, 894, 903
xphyle/paths.py        523      8    98%   67, 372, 606, 1067, 1101-1102, 1188, 1192
xphyle/progress.py      60     13    78%   19-20, 23, 53-56, 135-140
xphyle/types.py        214      6    97%   19-22, 401, 423, 443
xphyle/urls.py          42     10    76%   54, 63, 66, 80-82, 99-102, 110
xphyle/utils.py        451      4    99%   305, 1101-1104
--------------------------------------------------
TOTAL                 2304     78    97%


=================================== FAILURES ===================================
__________________________ FileTests.test_system_lzma __________________________

self = <unittest.case._Outcome object at 0x1041b7668>
test_case = <tests.test_formats.FileTests testMethod=test_system_lzma>
isTest = True

    @contextlib.contextmanager
    def testPartExecutor(self, test_case, isTest=False):
        old_success = self.success
        self.success = True
        try:
>           yield

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.FileTests testMethod=test_system_lzma>
result = <TestCaseFunction 'test_system_lzma'>

    def run(self, result=None):
        orig_result = result
        if result is None:
            result = self.defaultTestResult()
            startTestRun = getattr(result, 'startTestRun', None)
            if startTestRun is not None:
                startTestRun()
    
        result.startTest(self)
    
        testMethod = getattr(self, self._testMethodName)
        if (getattr(self.__class__, "__unittest_skip__", False) or
            getattr(testMethod, "__unittest_skip__", False)):
            # If the class or method was skipped.
            try:
                skip_why = (getattr(self.__class__, '__unittest_skip_why__', '')
                            or getattr(testMethod, '__unittest_skip_why__', ''))
                self._addSkip(result, self, skip_why)
            finally:
                result.stopTest(self)
            return
        expecting_failure_method = getattr(testMethod,
                                           "__unittest_expecting_failure__", False)
        expecting_failure_class = getattr(self,
                                          "__unittest_expecting_failure__", False)
        expecting_failure = expecting_failure_class or expecting_failure_method
        outcome = _Outcome(result)
        try:
            self._outcome = outcome
    
            with outcome.testPartExecutor(self):
                self.setUp()
            if outcome.success:
                outcome.expecting_failure = expecting_failure
                with outcome.testPartExecutor(self, isTest=True):
>                   testMethod()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:600: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.FileTests testMethod=test_system_lzma>

    @skipIf(xz_path is None, "'xz' not available")
    def test_system_lzma(self):
>       self.write_read_file('.xz', True)

tests/test_formats.py:255: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.FileTests testMethod=test_system_lzma>, ext = '.xz'
use_system = True, mode = 't'
content = 'Q*f`LQH)&6Y`Ub\\w-)]wYlbwM$]"XCft3X1)/ dH X1JC(m1<xlmQ268OX&r8iM~^sO)V`C0}.E:&+`]TFdpJ3m0C"}6DX"yaHS%1`k\\LQ3T#mbQZ.C...\'-]mq]x^abA_Kyr!nL!{]%)kc!$wMmyIjy]`p!>C4tD}8]N|l4P(*7 _^>E{.xRpCRP=xX$k,a\'<7?1ZuV(4Ko}xI_:d!r*a0z=\\w"0#}*!-Z`iw?8y'

    def write_read_file(self, ext, use_system, mode='t', content=None):
        if content is None:
            content = random_text() # generate 1 kb of random text
            if mode == 'b':
                content = b''.join(c.encode() for c in content)
        path = self.root.make_file(suffix=ext)
        fmt = get_format(ext)
>       write_file(fmt, path, use_system, content, 'w' + mode)

tests/test_formats.py:215: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fmt = <xphyle.formats.Lzma object at 0x10402fba8>
path = '/var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/tmpz02m22y2/0c0w_82b.xz'
use_system = True
content = 'Q*f`LQH)&6Y`Ub\\w-)]wYlbwM$]"XCft3X1)/ dH X1JC(m1<xlmQ268OX&r8iM~^sO)V`C0}.E:&+`]TFdpJ3m0C"}6DX"yaHS%1`k\\LQ3T#mbQZ.C...\'-]mq]x^abA_Kyr!nL!{]%)kc!$wMmyIjy]`p!>C4tD}8]N|l4P(*7 _^>E{.xRpCRP=xX$k,a\'<7?1ZuV(4Ko}xI_:d!r*a0z=\\w"0#}*!-Z`iw?8y'
mode = 'wt'

    def write_file(fmt, path, use_system, content, mode='wt'):
>       with fmt.open_file(path, mode=mode, use_system=use_system) as f:

tests/test_formats.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <xphyle.formats.Lzma object at 0x10402fba8>
path = '/var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/tmpz02m22y2/0c0w_82b.xz'
mode = wt, use_system = True, kwargs = {}, gzfile = None, bin_mode = wb

    def open_file(
            self, path: str, mode: ModeArg, use_system: bool = True,
            **kwargs) -> FileLike:
        """Opens a compressed file for reading or writing.
    
            If ``use_system`` is True and the system provides an accessible
            executable, then system-level compression is used. Otherwise defaults
            to using the python implementation.
    
            Args:
                path: The path of the file to open.
                mode: The file open mode.
                use_system: Whether to attempt to use system-level compression.
                kwargs: Additional arguments to pass to the python-level open
                    method, if system-level compression isn't used.
    
            Returns:
                A file-like object.
            """
        if isinstance(mode, str):
            mode = FileMode(mode)
    
        if use_system:
            # pylint: disable=redefined-variable-type
            gzfile = None # type: FileLikeInterface
            if mode.readable and self.can_use_system_compression:
                gzfile = SystemReader(
                    self.compress_path,
                    path,
                    self.get_command('d', src=path),
                    self.compress_name)
            elif not mode.readable and self.can_use_system_decompression:
                bin_mode = FileMode(
                    access=mode.access, coding=ModeCoding.BINARY)
                gzfile = SystemWriter(
                    self.decompress_path,
                    path,
                    bin_mode,
                    self.get_command('c'),
>                   self.decompress_name)

xphyle/formats.py:485: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <xphyle.formats.SystemWriter object at 0x1041b7588>, executable_path = ''
path = '/var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/tmpz02m22y2/0c0w_82b.xz'
mode = wb, command = ['', '-6', '-z', '-c'], executable_name = ''

    def __init__(
            self, executable_path: PathLike, path: PathLike,
            mode: ModeArg = 'w', command: List[str] = None,
            executable_name: str = None) -> None:
        super().__init__(path)
        self.executable_name = (
            executable_name or os.path.basename(str(executable_path)))
        self.command = command or [self.executable_name]
        if isinstance(mode, str):
            mode = FileMode(mode)
        self.outfile = open(str(path), mode.value)
        self.devnull = open(os.devnull, 'w')
        try:
            self.process = Popen(
                self.command, stdin=PIPE, stdout=self.outfile,
>               stderr=self.devnull)

xphyle/formats.py:197: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <subprocess.Popen object at 0x1041b79b0>, args = ['', '-6', '-z', '-c']
bufsize = -1, executable = None, stdin = -1
stdout = <_io.BufferedWriter name='/var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/tmpz02m22y2/0c0w_82b.xz'>
stderr = <_io.TextIOWrapper name='/dev/null' mode='w' encoding='utf-8'>
preexec_fn = None, close_fds = True, shell = False, cwd = None, env = None
universal_newlines = False, startupinfo = None, creationflags = 0
restore_signals = True, start_new_session = False, pass_fds = ()

    def __init__(self, args, bufsize=-1, executable=None,
                 stdin=None, stdout=None, stderr=None,
                 preexec_fn=None, close_fds=_PLATFORM_DEFAULT_CLOSE_FDS,
                 shell=False, cwd=None, env=None, universal_newlines=False,
                 startupinfo=None, creationflags=0,
                 restore_signals=True, start_new_session=False,
                 pass_fds=()):
        """Create new Popen instance."""
        _cleanup()
        # Held while anything is calling waitpid before returncode has been
        # updated to prevent clobbering returncode if wait() or poll() are
        # called from multiple threads at once.  After acquiring the lock,
        # code must re-check self.returncode to see if another thread just
        # finished a waitpid() call.
        self._waitpid_lock = threading.Lock()
    
        self._input = None
        self._communication_started = False
        if bufsize is None:
            bufsize = -1  # Restore default
        if not isinstance(bufsize, int):
            raise TypeError("bufsize must be an integer")
    
        if _mswindows:
            if preexec_fn is not None:
                raise ValueError("preexec_fn is not supported on Windows "
                                 "platforms")
            any_stdio_set = (stdin is not None or stdout is not None or
                             stderr is not None)
            if close_fds is _PLATFORM_DEFAULT_CLOSE_FDS:
                if any_stdio_set:
                    close_fds = False
                else:
                    close_fds = True
            elif close_fds and any_stdio_set:
                raise ValueError(
                        "close_fds is not supported on Windows platforms"
                        " if you redirect stdin/stdout/stderr")
        else:
            # POSIX
            if close_fds is _PLATFORM_DEFAULT_CLOSE_FDS:
                close_fds = True
            if pass_fds and not close_fds:
                warnings.warn("pass_fds overriding close_fds.", RuntimeWarning)
                close_fds = True
            if startupinfo is not None:
                raise ValueError("startupinfo is only supported on Windows "
                                 "platforms")
            if creationflags != 0:
                raise ValueError("creationflags is only supported on Windows "
                                 "platforms")
    
        self.args = args
        self.stdin = None
        self.stdout = None
        self.stderr = None
        self.pid = None
        self.returncode = None
        self.universal_newlines = universal_newlines
    
        # Input and output objects. The general principle is like
        # this:
        #
        # Parent                   Child
        # ------                   -----
        # p2cwrite   ---stdin--->  p2cread
        # c2pread    <--stdout---  c2pwrite
        # errread    <--stderr---  errwrite
        #
        # On POSIX, the child objects are file descriptors.  On
        # Windows, these are Windows file handles.  The parent objects
        # are file descriptors on both platforms.  The parent objects
        # are -1 when not using PIPEs. The child objects are -1
        # when not redirecting.
    
        (p2cread, p2cwrite,
         c2pread, c2pwrite,
         errread, errwrite) = self._get_handles(stdin, stdout, stderr)
    
        # We wrap OS handles *before* launching the child, otherwise a
        # quickly terminating child could make our fds unwrappable
        # (see #8458).
    
        if _mswindows:
            if p2cwrite != -1:
                p2cwrite = msvcrt.open_osfhandle(p2cwrite.Detach(), 0)
            if c2pread != -1:
                c2pread = msvcrt.open_osfhandle(c2pread.Detach(), 0)
            if errread != -1:
                errread = msvcrt.open_osfhandle(errread.Detach(), 0)
    
        if p2cwrite != -1:
            self.stdin = io.open(p2cwrite, 'wb', bufsize)
            if universal_newlines:
                self.stdin = io.TextIOWrapper(self.stdin, write_through=True,
                                              line_buffering=(bufsize == 1))
        if c2pread != -1:
            self.stdout = io.open(c2pread, 'rb', bufsize)
            if universal_newlines:
                self.stdout = io.TextIOWrapper(self.stdout)
        if errread != -1:
            self.stderr = io.open(errread, 'rb', bufsize)
            if universal_newlines:
                self.stderr = io.TextIOWrapper(self.stderr)
    
        self._closed_child_pipe_fds = False
        try:
            self._execute_child(args, executable, preexec_fn, close_fds,
                                pass_fds, cwd, env,
                                startupinfo, creationflags, shell,
                                p2cread, p2cwrite,
                                c2pread, c2pwrite,
                                errread, errwrite,
>                               restore_signals, start_new_session)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:950: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <subprocess.Popen object at 0x1041b79b0>, args = ['', '-6', '-z', '-c']
executable = b'', preexec_fn = None, close_fds = True, pass_fds = (), cwd = None
env = None, startupinfo = None, creationflags = 0, shell = False, p2cread = 38
p2cwrite = 39, c2pread = -1, c2pwrite = 36, errread = -1, errwrite = 37
restore_signals = True, start_new_session = False

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       pass_fds, cwd, env,
                       startupinfo, creationflags, shell,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite,
                       restore_signals, start_new_session):
        """Execute program (POSIX version)"""
    
        if isinstance(args, (str, bytes)):
            args = [args]
        else:
            args = list(args)
    
        if shell:
            args = ["/bin/sh", "-c"] + args
            if executable:
                args[0] = executable
    
        if executable is None:
            executable = args[0]
        orig_executable = executable
    
        # For transferring possible exec failure from child to parent.
        # Data format: "exception name:hex errno:description"
        # Pickle is not used; it is complex and involves memory allocation.
        errpipe_read, errpipe_write = os.pipe()
        # errpipe_write must not be in the standard io 0, 1, or 2 fd range.
        low_fds_to_close = []
        while errpipe_write < 3:
            low_fds_to_close.append(errpipe_write)
            errpipe_write = os.dup(errpipe_write)
        for low_fd in low_fds_to_close:
            os.close(low_fd)
        try:
            try:
                # We must avoid complex work that could involve
                # malloc or free in the child process to avoid
                # potential deadlocks, thus we do all this here.
                # and pass it to fork_exec()
    
                if env is not None:
                    env_list = [os.fsencode(k) + b'=' + os.fsencode(v)
                                for k, v in env.items()]
                else:
                    env_list = None  # Use execv instead of execve.
                executable = os.fsencode(executable)
                if os.path.dirname(executable):
                    executable_list = (executable,)
                else:
                    # This matches the behavior of os._execvpe().
                    executable_list = tuple(
                        os.path.join(os.fsencode(dir), executable)
                        for dir in os.get_exec_path(env))
                fds_to_keep = set(pass_fds)
                fds_to_keep.add(errpipe_write)
                self.pid = _posixsubprocess.fork_exec(
                        args, executable_list,
                        close_fds, sorted(fds_to_keep), cwd, env_list,
                        p2cread, p2cwrite, c2pread, c2pwrite,
                        errread, errwrite,
                        errpipe_read, errpipe_write,
                        restore_signals, start_new_session, preexec_fn)
                self._child_created = True
            finally:
                # be sure the FD is closed no matter what
                os.close(errpipe_write)
    
            # self._devnull is not always defined.
            devnull_fd = getattr(self, '_devnull', None)
            if p2cread != -1 and p2cwrite != -1 and p2cread != devnull_fd:
                os.close(p2cread)
            if c2pwrite != -1 and c2pread != -1 and c2pwrite != devnull_fd:
                os.close(c2pwrite)
            if errwrite != -1 and errread != -1 and errwrite != devnull_fd:
                os.close(errwrite)
            if devnull_fd is not None:
                os.close(devnull_fd)
            # Prevent a double close of these fds from __init__ on error.
            self._closed_child_pipe_fds = True
    
            # Wait for exec to fail or succeed; possibly raising an
            # exception (limited in size)
            errpipe_data = bytearray()
            while True:
                part = os.read(errpipe_read, 50000)
                errpipe_data += part
                if not part or len(errpipe_data) > 50000:
                    break
        finally:
            # be sure the FD is closed no matter what
            os.close(errpipe_read)
    
        if errpipe_data:
            try:
                os.waitpid(self.pid, 0)
            except ChildProcessError:
                pass
            try:
                exception_name, hex_errno, err_msg = (
                        errpipe_data.split(b':', 2))
            except ValueError:
                exception_name = b'SubprocessError'
                hex_errno = b'0'
                err_msg = (b'Bad exception data from child: ' +
                           repr(errpipe_data))
            child_exception_type = getattr(
                    builtins, exception_name.decode('ascii'),
                    SubprocessError)
            err_msg = err_msg.decode(errors="surrogatepass")
            if issubclass(child_exception_type, OSError) and hex_errno:
                errno_num = int(hex_errno, 16)
                child_exec_never_called = (err_msg == "noexec")
                if child_exec_never_called:
                    err_msg = ""
                if errno_num != 0:
                    err_msg = os.strerror(errno_num)
                    if errno_num == errno.ENOENT:
                        if child_exec_never_called:
                            # The error must be from chdir(cwd).
                            err_msg += ': ' + repr(cwd)
                        else:
                            err_msg += ': ' + repr(orig_executable)
>               raise child_exception_type(errno_num, err_msg)
E               PermissionError: [Errno 13] Permission denied

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py:1544: PermissionError
============================== 2 tests deselected ==============================
======== 1 failed, 129 passed, 3 skipped, 2 deselected in 6.12 seconds =========

**Comment by jdidion** [comment]
This is fixed in v3.0.3. lzma/xz is either not installed on your system or you don't have executable permissions. I discovered a bug that was preventing xphyle from recognizing this and silently defaulting to the python library implementation.

**Comment by ctb** [comment]
new failed test with latest master:


python -m pytest -m "not perf" --cov --cov-report term-missing --full-trace tests
============================= test session starts ==============================
platform darwin -- Python 3.5.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/t/dev/xphyle, inifile:
plugins: cov-2.5.1
collected 135 items

tests/test_formats.py .s......Fss.........s.....
tests/test_paths.py ...................................
tests/test_progress.py ...
tests/test_types.py .....
tests/test_urls.py ....
tests/test_utils.py .....................................
tests/test_xphyle.py .......................

---------- coverage: platform darwin, python 3.5.1-final-0 -----------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
xphyle/__init__.py     491     14    97%   285, 291, 391, 395-405, 612, 684, 826
xphyle/formats.py      524     27    95%   191, 292, 298, 508, 540-541, 640-641, 772, 789, 831-841, 893, 902, 959-960, 965, 967
xphyle/paths.py        523      8    98%   67, 372, 606, 1067, 1101-1102, 1188, 1192
xphyle/progress.py      60     13    78%   19-20, 23, 53-56, 135-140
xphyle/types.py        214      6    97%   19-22, 401, 423, 443
xphyle/urls.py          42     10    76%   54, 63, 66, 80-82, 99-102, 110
xphyle/utils.py        451      4    99%   305, 1101-1104
--------------------------------------------------
TOTAL                 2305     82    96%


=================================== FAILURES ===================================
__________________________ CompressionTests.test_lzma __________________________

self = <unittest.case._Outcome object at 0x1041a9518>
test_case = <tests.test_formats.CompressionTests testMethod=test_lzma>
isTest = True

    @contextlib.contextmanager
    def testPartExecutor(self, test_case, isTest=False):
        old_success = self.success
        self.success = True
        try:
>           yield

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.CompressionTests testMethod=test_lzma>
result = <TestCaseFunction 'test_lzma'>

    def run(self, result=None):
        orig_result = result
        if result is None:
            result = self.defaultTestResult()
            startTestRun = getattr(result, 'startTestRun', None)
            if startTestRun is not None:
                startTestRun()
    
        result.startTest(self)
    
        testMethod = getattr(self, self._testMethodName)
        if (getattr(self.__class__, "__unittest_skip__", False) or
            getattr(testMethod, "__unittest_skip__", False)):
            # If the class or method was skipped.
            try:
                skip_why = (getattr(self.__class__, '__unittest_skip_why__', '')
                            or getattr(testMethod, '__unittest_skip_why__', ''))
                self._addSkip(result, self, skip_why)
            finally:
                result.stopTest(self)
            return
        expecting_failure_method = getattr(testMethod,
                                           "__unittest_expecting_failure__", False)
        expecting_failure_class = getattr(self,
                                          "__unittest_expecting_failure__", False)
        expecting_failure = expecting_failure_class or expecting_failure_method
        outcome = _Outcome(result)
        try:
            self._outcome = outcome
    
            with outcome.testPartExecutor(self):
                self.setUp()
            if outcome.success:
                outcome.expecting_failure = expecting_failure
                with outcome.testPartExecutor(self, isTest=True):
>                   testMethod()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:600: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.CompressionTests testMethod=test_lzma>

    def test_lzma(self):
        xz = get_format('xz')
        self._test_format(xz)
        self.assertEqual(xz.default_ext, 'xz')
        self.assertEqual(
            xz.get_command('c', compresslevel=5),
>           [xz_path, '-5', '-z', '-c'])

tests/test_formats.py:175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.CompressionTests testMethod=test_lzma>
first = ['None', '-5', '-z', '-c'], second = [None, '-5', '-z', '-c']
msg = None

    def assertEqual(self, first, second, msg=None):
        """Fail if the two objects are unequal as determined by the '=='
               operator.
            """
        assertion_func = self._getAssertEqualityFunc(first, second)
>       assertion_func(first, second, msg=msg)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:820: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.CompressionTests testMethod=test_lzma>
list1 = ['None', '-5', '-z', '-c'], list2 = [None, '-5', '-z', '-c'], msg = None

    def assertListEqual(self, list1, list2, msg=None):
        """A list-specific equality assertion.
    
            Args:
                list1: The first list to compare.
                list2: The second list to compare.
                msg: Optional message to use on failure instead of a list of
                        differences.
    
            """
>       self.assertSequenceEqual(list1, list2, msg, seq_type=list)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:1018: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.CompressionTests testMethod=test_lzma>
seq1 = ['None', '-5', '-z', '-c'], seq2 = [None, '-5', '-z', '-c']
msg = "Lists differ: ['None', '-5', '-z', '-c'] != [None, '-5', '-z', '-c']\n\nFirst differing element 0:\nNone\nNone\n\n- ['None', '-5', '-z', '-c']\n?  -    -\n\n+ [None, '-5', '-z', '-c']"
seq_type = <class 'list'>

    def assertSequenceEqual(self, seq1, seq2, msg=None, seq_type=None):
        """An equality assertion for ordered sequences (like lists and tuples).
    
            For the purposes of this function, a valid ordered sequence type is one
            which can be indexed, has a length, and has an equality operator.
    
            Args:
                seq1: The first sequence to compare.
                seq2: The second sequence to compare.
                seq_type: The expected datatype of the sequences, or None if no
                        datatype should be enforced.
                msg: Optional message to use on failure instead of a list of
                        differences.
            """
        if seq_type is not None:
            seq_type_name = seq_type.__name__
            if not isinstance(seq1, seq_type):
                raise self.failureException('First sequence is not a %s: %s'
                                        % (seq_type_name, safe_repr(seq1)))
            if not isinstance(seq2, seq_type):
                raise self.failureException('Second sequence is not a %s: %s'
                                        % (seq_type_name, safe_repr(seq2)))
        else:
            seq_type_name = "sequence"
    
        differing = None
        try:
            len1 = len(seq1)
        except (TypeError, NotImplementedError):
            differing = 'First %s has no length.    Non-sequence?' % (
                    seq_type_name)
    
        if differing is None:
            try:
                len2 = len(seq2)
            except (TypeError, NotImplementedError):
                differing = 'Second %s has no length.    Non-sequence?' % (
                        seq_type_name)
    
        if differing is None:
            if seq1 == seq2:
                return
    
            differing = '%ss differ: %s != %s\n' % (
                    (seq_type_name.capitalize(),) +
                    _common_shorten_repr(seq1, seq2))
    
            for i in range(min(len1, len2)):
                try:
                    item1 = seq1[i]
                except (TypeError, IndexError, NotImplementedError):
                    differing += ('\nUnable to index element %d of first %s\n' %
                                 (i, seq_type_name))
                    break
    
                try:
                    item2 = seq2[i]
                except (TypeError, IndexError, NotImplementedError):
                    differing += ('\nUnable to index element %d of second %s\n' %
                                 (i, seq_type_name))
                    break
    
                if item1 != item2:
                    differing += ('\nFirst differing element %d:\n%s\n%s\n' %
                                 (i, item1, item2))
                    break
            else:
                if (len1 == len2 and seq_type is None and
                    type(seq1) != type(seq2)):
                    # The sequences are the same, but have differing types.
                    return
    
            if len1 > len2:
                differing += ('\nFirst %s contains %d additional '
                             'elements.\n' % (seq_type_name, len1 - len2))
                try:
                    differing += ('First extra element %d:\n%s\n' %
                                  (len2, seq1[len2]))
                except (TypeError, IndexError, NotImplementedError):
                    differing += ('Unable to index element %d '
                                  'of first %s\n' % (len2, seq_type_name))
            elif len1 < len2:
                differing += ('\nSecond %s contains %d additional '
                             'elements.\n' % (seq_type_name, len2 - len1))
                try:
                    differing += ('First extra element %d:\n%s\n' %
                                  (len1, seq2[len1]))
                except (TypeError, IndexError, NotImplementedError):
                    differing += ('Unable to index element %d '
                                  'of second %s\n' % (len1, seq_type_name))
        standardMsg = differing
        diffMsg = '\n' + '\n'.join(
            difflib.ndiff(pprint.pformat(seq1).splitlines(),
                          pprint.pformat(seq2).splitlines()))
    
        standardMsg = self._truncateMessage(standardMsg, diffMsg)
        msg = self._formatMessage(msg, standardMsg)
>       self.fail(msg)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:1000: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.test_formats.CompressionTests testMethod=test_lzma>
msg = "Lists differ: ['None', '-5', '-z', '-c'] != [None, '-5', '-z', '-c']\n\nFirst differing element 0:\nNone\nNone\n\n- ['None', '-5', '-z', '-c']\n?  -    -\n\n+ [None, '-5', '-z', '-c']"

    def fail(self, msg=None):
        """Fail immediately, with the given message."""
>       raise self.failureException(msg)
E       AssertionError: Lists differ: ['None', '-5', '-z', '-c'] != [None, '-5', '-z', '-c']
E       
E       First differing element 0:
E       None
E       None
E       
E       - ['None', '-5', '-z', '-c']
E       ?  -    -
E       
E       + [None, '-5', '-z', '-c']

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:665: AssertionError
============================== 2 tests deselected ==============================
======== 1 failed, 128 passed, 4 skipped, 2 deselected in 7.10 seconds =========
make: *** [test] Error 1

**Comment by jdidion** [comment]
Give it a try now. I’m just skipping tests if the required executable is not installed on the local machine.

**Comment by ctb** [comment]
works!
