### ISSUE TITLE
Problem reading a zstd file

### ISSUE THREAD

**Issue by standage** [jdidion/xphyle#53]
Hi @jdidion, great project!

I was just testing support for the various compression algorithms, and I ran into a problem with zstd.

```
$ shasum cds.fna
1afeb1e5ab0dac1385942cc1399e60e9efa7f5c1  cds.fna
$ zstd < cds.fna > cds.fna.zst
$ zstd -dc cds.fna.zst | shasum
cds.fna.zst         : 871750 bytes                                             
1afeb1e5ab0dac1385942cc1399e60e9efa7f5c1  -
$ python
Python 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:22:07) 
[Clang 10.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xphyle
>>> with xphyle.open_("cds.fna.zst") as fh:
...   data = fh.read().strip()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/standage/anaconda3/envs/xphyle/lib/python3.7/site-packages/xphyle/__init__.py", line 269, in read
    return self._fileobj.read(size)
  File "/Users/standage/anaconda3/envs/xphyle/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte
```

Files attached. (I had to add a .txt extension for GitHub to accept)
- [cds.fna.txt](https://github.com/jdidion/xphyle/files/6275449/cds.fna.txt)
- [cds.fna.zst.txt](https://github.com/jdidion/xphyle/files/6275451/cds.fna.zst.txt)

Am I doing something wrong?

**Comment by jdidion** [comment]
This will be fixed in the next release. There were two problems: the magic bytes sequence was wrong, and there was no fallback to determine the compression from the file extension. I've fixed both issues.

**Comment by standage** [comment]
Wonderful, thank you! I'm subscribed to the repo so I look forward to the release announcement.
