### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by adrienyhuel** [jdidion/xphyle#67]
When I run xphyle with python 3.10, I have an error : 

  File "/home/mft/.local/lib/python3.10/site-packages/xphyle/utils.py", line 8, in <module>
    from collections import OrderedDict, Sized
ImportError: cannot import name 'Sized' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

It seems like in python 3.10, Sized moved from collections to collections.abc

Maybe there's others incompatibilties.

Could you update xphyle which is a great tool, to support python 3.10 ?

**Comment by jdidion** [comment]
Will be fixed in the next release.
